# Generated by Django 3.1 on 2020-08-31 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='자소서 내용')),
                ('company_name', models.CharField(max_length=120, verbose_name='회사명')),
                ('department_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='직무분야명')),
                ('pass_fail_result', models.CharField(choices=[('PASS', 'PASS'), ('HOLD', 'HOLD'), ('FAIL', 'FAIL')], default='HOLD', max_length=5)),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='FreeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plagiarism_percent', models.FloatField(max_length=100, verbose_name='표절 확률')),
                ('pass_percent', models.FloatField(max_length=100, verbose_name='합격 확률')),
                ('grammar_contents', models.TextField(null=True, verbose_name='맞춤법 수정본')),
                ('correction_contents', models.TextField(null=True, verbose_name='첨삭')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deepsquareapp.selfintroduction', verbose_name='자소서 아이디')),
            ],
        ),
    ]
