# Generated by Django 3.1 on 2020-09-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deepsquareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('corporate_name', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='회사명')),
                ('corporate_vision', models.TextField(null=True, verbose_name='기업 비전')),
            ],
        ),
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duties_name', models.CharField(max_length=120, verbose_name='직무명')),
                ('duties_feature', models.TextField(null=True, verbose_name='직무 특성')),
            ],
        ),
        migrations.CreateModel(
            name='Corporate_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_keyword', models.CharField(max_length=30, null=True, verbose_name='기업 키워드')),
                ('corporate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deepsquareapp.corporate', verbose_name='회사명')),
            ],
        ),
    ]
