# Generated by Django 3.1 on 2020-09-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepsquareapp', '0002_corporate_corporate_keyword_duties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_name', models.CharField(max_length=30, verbose_name='역량명')),
                ('competency_define', models.TextField(verbose_name='역량 정의')),
            ],
        ),
    ]
