# Generated by Django 3.1 on 2020-09-16 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deepsquareapp', '0003_competency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
